### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by idavidrein** [JakobBritton/Project-Gladius#1]
- [x] Create array to randomly choose from when mating
- [x] Match mates together
- [x] Create "generations" and battles (match up individuals for fighting, once all fights are done put them into aforementioned array for mating). 

- [x] Redo fitness?

**Comment by JakobBritton** [comment]
Oh wow, this can be quite convenient.

**Comment by idavidrein** [comment]
Yeah, definitely, I'm glad I found it
